# Generated by Django 5.1.6 on 2025-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('hiredate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
            ],
        ),
    ]
